blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://asahilinux.org/community/
    about: |
      If you are after general information or advice, feel free
      to ask in our community chatrooms, available on IRC and
      Matrix.
  - name: r/AsahiLinux
    url: https://reddit.com/r/AsahiLinux
    about: |
      We also have an official subreddit if you prefer to engage
      with the community there.
